name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Docker up
      working-directory: ./selenium
      run: docker-compose up -d
  
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      working-directory: ./selenium
      run: npm install

    - name: Check if docker is up
      run: |
        while ! curl -s http://localhost:8080/wd/hub/status | jq -r .value.ready 2>/dev/null | grep -q true; do
          sleep 5
        done

    - name: Run Selenium Tests
      working-directory: ./selenium
      run: npm test
